version: '3.4'
services:

  stockapplicationapi:
    image: ${DOCKER_REGISTRY-}stockapplicationapi
    build:
      context: .
      dockerfile: StockApplicationApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT__SigningKey=${JWT_SIGNING_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
    depends_on:
      postgres:
        condition: service_healthy   # ← waits for postgres to be TRULY ready
      redis:
        condition: service_started
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: stockapp-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres:
    image: postgres:16-alpine
    container_name: stockapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s       # check every 5 seconds
      timeout: 5s        # wait max 5s for response
      retries: 5         # try 5 times before giving up
      start_period: 10s  # give postgres 10s to boot before checking
    
  redis:
    image: redis:7-alpine
    container_name: stockapp-cache
    # ports:
    #   - "6379:6379"

volumes:
  postgresData: