version: '3.4'
services:
  stockapplicationapi:
    image: ${DOCKER_REGISTRY-}stockapplicationapi
    build:
      context: .
      dockerfile: StockApplicationApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=stock_database;Username=admin;Password=secret_password_here
      - ConnectionStrings__RedisConnection=redis:6379,abortConnect=false
      - JWT__Issuer=http://localhost:8080/
      - JWT__Audience=http://localhost:8080/
      - JWT__SigningKey=7f8b9c2a5d1e4b3a8f6c0d9e8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b
    depends_on:
      postgres:
        condition: service_healthy   # ← waits for postgres to be TRULY ready
      redis:
        condition: service_started
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: stockapp-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres:
    image: postgres:16-alpine
    container_name: stockapp-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret_password_here
      POSTGRES_DB: stock_database
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d stock_database"]
      interval: 5s       # check every 5 seconds
      timeout: 5s        # wait max 5s for response
      retries: 5         # try 5 times before giving up
      start_period: 10s  # give postgres 10s to boot before checking
    
  redis:
    image: redis:7-alpine
    container_name: stockapp-cache
    ports:
      - "6379:6379"

volumes:
  postgresData: