// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApplicationApi.Database;

#nullable disable

namespace StockApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514112023_MigrationAfterChangesInRelations")]
    partial class MigrationAfterChangesInRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Nvidia",
                            Industry = "Semiconductors",
                            LastDiv = 0.16m,
                            MarketCap = 4300000000000L,
                            Purchase = 188.60m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Apple Inc",
                            Industry = "Technology",
                            LastDiv = 0.24m,
                            MarketCap = 3800000000000L,
                            Purchase = 260.45m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet",
                            Industry = "Technology",
                            LastDiv = 0.00m,
                            MarketCap = 3700000000000L,
                            Purchase = 315.70m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Microsoft",
                            Industry = "Technology",
                            LastDiv = 0.68m,
                            MarketCap = 2800000000000L,
                            Purchase = 370.80m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 2600000000000L,
                            Purchase = 238.40m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "TSMC",
                            Industry = "Semiconductors",
                            LastDiv = 1.20m,
                            MarketCap = 1900000000000L,
                            Purchase = 370.60m,
                            Symbol = "TSM"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Broadcom",
                            Industry = "Semiconductors",
                            LastDiv = 2.10m,
                            MarketCap = 1800000000000L,
                            Purchase = 371.50m,
                            Symbol = "AVGO"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Meta Platforms",
                            Industry = "Social Media",
                            LastDiv = 0.50m,
                            MarketCap = 1600000000000L,
                            Purchase = 629.80m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Tesla",
                            Industry = "Automotive",
                            LastDiv = 0.00m,
                            MarketCap = 1300000000000L,
                            Purchase = 348.90m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Berkshire Hathaway",
                            Industry = "Financials",
                            LastDiv = 0.00m,
                            MarketCap = 1030000000000L,
                            Purchase = 479.90m,
                            Symbol = "BRK-B"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Walmart",
                            Industry = "Retail",
                            LastDiv = 0.80m,
                            MarketCap = 1010000000000L,
                            Purchase = 126.70m,
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Eli Lilly",
                            Industry = "Healthcare",
                            LastDiv = 1.30m,
                            MarketCap = 887000000000L,
                            Purchase = 939.40m,
                            Symbol = "LLY"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "JPMorgan Chase",
                            Industry = "Financials",
                            LastDiv = 1.15m,
                            MarketCap = 835000000000L,
                            Purchase = 309.80m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Visa",
                            Industry = "Financials",
                            LastDiv = 0.52m,
                            MarketCap = 586000000000L,
                            Purchase = 304.30m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "Exxon Mobil",
                            Industry = "Energy",
                            LastDiv = 0.95m,
                            MarketCap = 633000000000L,
                            Purchase = 152.50m,
                            Symbol = "XOM"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "ASML Holding",
                            Industry = "Semiconductors",
                            LastDiv = 1.75m,
                            MarketCap = 580000000000L,
                            Purchase = 1478.00m,
                            Symbol = "ASML"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Tencent",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 578000000000L,
                            Purchase = 63.90m,
                            Symbol = "TCEHY"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Johnson & Johnson",
                            Industry = "Healthcare",
                            LastDiv = 1.19m,
                            MarketCap = 574000000000L,
                            Purchase = 238.40m,
                            Symbol = "JNJ"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Mastercard",
                            Industry = "Financials",
                            LastDiv = 0.66m,
                            MarketCap = 445000000000L,
                            Purchase = 498.60m,
                            Symbol = "MA"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Costco",
                            Industry = "Retail",
                            LastDiv = 1.02m,
                            MarketCap = 443000000000L,
                            Purchase = 998.40m,
                            Symbol = "COST"
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "Netflix",
                            Industry = "Entertainment",
                            LastDiv = 0.00m,
                            MarketCap = 436000000000L,
                            Purchase = 103.00m,
                            Symbol = "NFLX"
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "AMD",
                            Industry = "Semiconductors",
                            LastDiv = 0.00m,
                            MarketCap = 399000000000L,
                            Purchase = 245.00m,
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "Oracle",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 397000000000L,
                            Purchase = 138.00m,
                            Symbol = "ORCL"
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "Chevron",
                            Industry = "Energy",
                            LastDiv = 1.51m,
                            MarketCap = 375000000000L,
                            Purchase = 188.50m,
                            Symbol = "CVX"
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "Home Depot",
                            Industry = "Retail",
                            LastDiv = 2.25m,
                            MarketCap = 335000000000L,
                            Purchase = 337.30m,
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "Coca-Cola",
                            Industry = "Beverages",
                            LastDiv = 0.48m,
                            MarketCap = 333000000000L,
                            Purchase = 77.40m,
                            Symbol = "KO"
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "AbbVie",
                            Industry = "Healthcare",
                            LastDiv = 1.55m,
                            MarketCap = 367000000000L,
                            Purchase = 207.90m,
                            Symbol = "ABBV"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Bank of America",
                            Industry = "Financials",
                            LastDiv = 0.24m,
                            MarketCap = 377000000000L,
                            Purchase = 52.50m,
                            Symbol = "BAC"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Procter & Gamble",
                            Industry = "Consumer Goods",
                            LastDiv = 0.94m,
                            MarketCap = 339000000000L,
                            Purchase = 145.10m,
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "PepsiCo",
                            Industry = "Beverages",
                            LastDiv = 1.26m,
                            MarketCap = 231000000000L,
                            Purchase = 168.20m,
                            Symbol = "PEP"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "Salesforce",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 285000000000L,
                            Purchase = 295.40m,
                            Symbol = "CRM"
                        },
                        new
                        {
                            Id = 32,
                            CompanyName = "Adobe",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 262000000000L,
                            Purchase = 585.10m,
                            Symbol = "ADBE"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Nike",
                            Industry = "Apparel",
                            LastDiv = 0.37m,
                            MarketCap = 153000000000L,
                            Purchase = 101.50m,
                            Symbol = "NKE"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Disney",
                            Industry = "Entertainment",
                            LastDiv = 0.30m,
                            MarketCap = 205000000000L,
                            Purchase = 112.80m,
                            Symbol = "DIS"
                        },
                        new
                        {
                            Id = 35,
                            CompanyName = "Toyota",
                            Industry = "Automotive",
                            LastDiv = 0.85m,
                            MarketCap = 274000000000L,
                            Purchase = 210.60m,
                            Symbol = "TM"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "AstraZeneca",
                            Industry = "Healthcare",
                            LastDiv = 1.90m,
                            MarketCap = 316000000000L,
                            Purchase = 204.00m,
                            Symbol = "AZN"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Intel",
                            Industry = "Semiconductors",
                            LastDiv = 0.12m,
                            MarketCap = 313000000000L,
                            Purchase = 62.30m,
                            Symbol = "INTC"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Palantir",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 306000000000L,
                            Purchase = 128.00m,
                            Symbol = "PLTR"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Alibaba",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 304000000000L,
                            Purchase = 127.30m,
                            Symbol = "BABA"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Pfizer",
                            Industry = "Healthcare",
                            LastDiv = 0.42m,
                            MarketCap = 161000000000L,
                            Purchase = 28.50m,
                            Symbol = "PFE"
                        },
                        new
                        {
                            Id = 41,
                            CompanyName = "Caterpillar",
                            Industry = "Industrials",
                            LastDiv = 1.30m,
                            MarketCap = 370000000000L,
                            Purchase = 790.60m,
                            Symbol = "CAT"
                        },
                        new
                        {
                            Id = 42,
                            CompanyName = "Cisco",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 324000000000L,
                            Purchase = 82.20m,
                            Symbol = "CSCO"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "IBM",
                            Industry = "Technology",
                            LastDiv = 1.66m,
                            MarketCap = 170000000000L,
                            Purchase = 185.30m,
                            Symbol = "IBM"
                        },
                        new
                        {
                            Id = 44,
                            CompanyName = "Goldman Sachs",
                            Industry = "Financials",
                            LastDiv = 2.75m,
                            MarketCap = 269000000000L,
                            Purchase = 907.80m,
                            Symbol = "GS"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "McDonald's",
                            Industry = "Restaurants",
                            LastDiv = 1.67m,
                            MarketCap = 210000000000L,
                            Purchase = 290.40m,
                            Symbol = "MCD"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Starbucks",
                            Industry = "Restaurants",
                            LastDiv = 0.57m,
                            MarketCap = 105000000000L,
                            Purchase = 92.50m,
                            Symbol = "SBUX"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "UPS",
                            Industry = "Logistics",
                            LastDiv = 1.63m,
                            MarketCap = 125000000000L,
                            Purchase = 145.80m,
                            Symbol = "UPS"
                        },
                        new
                        {
                            Id = 48,
                            CompanyName = "Blackstone",
                            Industry = "Financials",
                            LastDiv = 0.82m,
                            MarketCap = 158000000000L,
                            Purchase = 130.20m,
                            Symbol = "BX"
                        },
                        new
                        {
                            Id = 49,
                            CompanyName = "Qualcomm",
                            Industry = "Semiconductors",
                            LastDiv = 0.80m,
                            MarketCap = 190000000000L,
                            Purchase = 170.50m,
                            Symbol = "QCOM"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "Abbott Labs",
                            Industry = "Healthcare",
                            LastDiv = 0.55m,
                            MarketCap = 201000000000L,
                            Purchase = 115.40m,
                            Symbol = "ABT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", "AppUser")
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApplicationApi.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockApplicationApi.Models.AppUser", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
