// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockApplicationApi.Database;

#nullable disable

namespace StockApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602091634_MadeChanges")]
    partial class MadeChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Blackwell GPU demand is insane, this stock has legs.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 1,
                            Title = "Strong Buy"
                        },
                        new
                        {
                            Id = 2,
                            Content = "AI infrastructure spending keeps benefiting Nvidia. Not selling.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 1,
                            Title = "Long-term Hold"
                        },
                        new
                        {
                            Id = 3,
                            Content = "P/E is getting stretched. I trimmed my position last week.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 1,
                            Title = "Overvalued?"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Every pullback on NVDA has been a buying opportunity so far.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 1,
                            Title = "Dip Buyer"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Services revenue is great but hardware growth is slowing.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 2,
                            Title = "Cautious"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Apple Intelligence could be a huge catalyst in 2025.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 2,
                            Title = "Bullish on AI"
                        },
                        new
                        {
                            Id = 7,
                            Content = "AI search could cannibalize their core business long-term.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 3,
                            Title = "Ad Revenue Concern"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Copilot integration across Office 365 is a massive moat.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 4,
                            Title = "AI Leader"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Azure growth numbers keep impressing every quarter.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 4,
                            Title = "Azure Growth"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Not flashy but MSFT keeps quietly raising its dividend.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 4,
                            Title = "Solid Dividend"
                        },
                        new
                        {
                            Id = 11,
                            Content = "AWS margins are expanding nicely. Best cloud play out there.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 5,
                            Title = "AWS Dominance"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Cost-cutting in logistics is finally showing up in earnings.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 5,
                            Title = "Retail Efficiency"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Every advanced chip runs through TSMC. Truly irreplaceable.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 6,
                            Title = "Essential Monopoly"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Taiwan tensions are a real risk factor to keep watching.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 6,
                            Title = "Geopolitical Risk"
                        },
                        new
                        {
                            Id = 15,
                            Content = "US fab expansion reduces geopolitical risk over time.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 6,
                            Title = "Arizona Expansion"
                        },
                        new
                        {
                            Id = 16,
                            Content = "TSMC keeps raising wafer prices and customers just pay it.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 6,
                            Title = "Pricing Power"
                        },
                        new
                        {
                            Id = 17,
                            Content = "AVGO's custom ASIC business for hyperscalers is quietly booming.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 7,
                            Title = "Custom AI Chips"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Their ad targeting is best-in-class and only getting stronger.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 8,
                            Title = "Ad Machine"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Metaverse spending is still a massive cash burn with no end in sight.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 8,
                            Title = "Reality Labs Drain"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Open-sourcing Llama is a smart long-term moat-building play.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 8,
                            Title = "Llama Strategy"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Hard to justify this price on auto earnings alone.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 9,
                            Title = "Valuation Stretched"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Full Self-Driving could completely re-rate this stock if it works.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 9,
                            Title = "FSD Potential"
                        },
                        new
                        {
                            Id = 23,
                            Content = "Buffett's cash pile gives him incredible flexibility right now.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 10,
                            Title = "Safe Haven"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Walmart's grocery dominance is extremely hard to compete with.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 11,
                            Title = "Retail Powerhouse"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Walmart+ and online growth are finally clicking into place.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 11,
                            Title = "E-Commerce Pivot"
                        },
                        new
                        {
                            Id = 26,
                            Content = "Mounjaro and Zepbound demand far outpaces supply right now.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 12,
                            Title = "GLP-1 Leader"
                        },
                        new
                        {
                            Id = 27,
                            Content = "The premium is massive but the pipeline arguably justifies it.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 12,
                            Title = "High Valuation"
                        },
                        new
                        {
                            Id = 28,
                            Content = "Manufacturing capacity is the only thing limiting LLY growth.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 12,
                            Title = "Supply Ramp"
                        },
                        new
                        {
                            Id = 29,
                            Content = "The total addressable market for obesity drugs is enormous.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 12,
                            Title = "Obesity Market"
                        },
                        new
                        {
                            Id = 30,
                            Content = "Dimon keeps executing flawlessly in any rate environment.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 13,
                            Title = "Best Bank"
                        },
                        new
                        {
                            Id = 31,
                            Content = "NII may compress if the Fed cuts rates faster than expected.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 13,
                            Title = "Rate Sensitivity"
                        },
                        new
                        {
                            Id = 32,
                            Content = "JPM always seems to come out of downturns stronger than peers.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 13,
                            Title = "Fortress Balance Sheet"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Visa's margins and free cash flow are simply phenomenal.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 14,
                            Title = "Cash Flow Beast"
                        },
                        new
                        {
                            Id = 34,
                            Content = "XOM's dividend history is about as reliable as it gets.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 15,
                            Title = "Dividend Rock"
                        },
                        new
                        {
                            Id = 35,
                            Content = "Pioneer acquisition is boosting Permian production nicely.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 15,
                            Title = "Pioneer Synergies"
                        },
                        new
                        {
                            Id = 36,
                            Content = "ASML is literally the only company making EUV lithography machines.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 16,
                            Title = "EUV Monopoly"
                        },
                        new
                        {
                            Id = 37,
                            Content = "Export restrictions to China are a real headwind worth watching.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 16,
                            Title = "China Export Risk"
                        },
                        new
                        {
                            Id = 38,
                            Content = "Next-gen High NA EUV tools will keep ASML ahead for a decade.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 16,
                            Title = "High NA EUV"
                        },
                        new
                        {
                            Id = 39,
                            Content = "The order backlog is enormous — revenue visibility is exceptional.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 16,
                            Title = "Backlog Monster"
                        },
                        new
                        {
                            Id = 40,
                            Content = "Chinese tech regulation remains an unpredictable ongoing concern.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 17,
                            Title = "Regulatory Overhang"
                        },
                        new
                        {
                            Id = 41,
                            Content = "JNJ is a classic defensive hold with steady reliable dividends.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 18,
                            Title = "Defensive Pick"
                        },
                        new
                        {
                            Id = 42,
                            Content = "Post-Kenvue spinoff JNJ is sharper and more focused than ever.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 18,
                            Title = "MedTech Focus"
                        },
                        new
                        {
                            Id = 43,
                            Content = "Mastercard benefits every single time a new market goes cashless.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 19,
                            Title = "Global Expansion"
                        },
                        new
                        {
                            Id = 44,
                            Content = "Travel recovery has been a huge tailwind for Mastercard.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 19,
                            Title = "Cross-border Revenue"
                        },
                        new
                        {
                            Id = 45,
                            Content = "MA is positioning itself well even in a crypto payments world.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 19,
                            Title = "Crypto Hedge"
                        },
                        new
                        {
                            Id = 46,
                            Content = "The 90%+ membership renewal rate is one of retail's best moats.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 20,
                            Title = "Membership Model"
                        },
                        new
                        {
                            Id = 47,
                            Content = "Paid sharing drove subscriber growth well beyond expectations.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 21,
                            Title = "Password Crackdown Win"
                        },
                        new
                        {
                            Id = 48,
                            Content = "The ad-supported tier is a whole new revenue stream with big upside.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 21,
                            Title = "Ad Tier Growth"
                        },
                        new
                        {
                            Id = 49,
                            Content = "MI300X is gaining real traction against Nvidia in AI workloads.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 22,
                            Title = "Data Center Push"
                        },
                        new
                        {
                            Id = 50,
                            Content = "Gaming GPU and laptop CPU cycles look set to recover this year.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 22,
                            Title = "PC Recovery"
                        },
                        new
                        {
                            Id = 51,
                            Content = "EPYC server CPUs keep taking share from Intel in data centers.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 22,
                            Title = "EPYC Dominance"
                        },
                        new
                        {
                            Id = 52,
                            Content = "AMD's turnaround under Lisa Su is one of tech's best CEO stories.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 22,
                            Title = "Lisa Su Effect"
                        },
                        new
                        {
                            Id = 53,
                            Content = "OCI is winning large AI training contracts no one expected.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 23,
                            Title = "Cloud Acceleration"
                        },
                        new
                        {
                            Id = 54,
                            Content = "The Hess acquisition brings great Guyana deepwater assets onboard.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 24,
                            Title = "Hess Deal"
                        },
                        new
                        {
                            Id = 55,
                            Content = "CVX's buyback program is among the best in the energy sector.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 24,
                            Title = "Shareholder Returns"
                        },
                        new
                        {
                            Id = 56,
                            Content = "Everything hinges on crude prices — keep an eye on OPEC+ decisions.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 24,
                            Title = "Oil Price Watch"
                        },
                        new
                        {
                            Id = 57,
                            Content = "HD will benefit big when mortgage rates eventually come down.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 25,
                            Title = "Housing Cycle"
                        },
                        new
                        {
                            Id = 58,
                            Content = "The Pro contractor segment is a high-margin and growing revenue driver.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 25,
                            Title = "Pro Segment"
                        },
                        new
                        {
                            Id = 59,
                            Content = "KO has raised its dividend for over 60 consecutive years. Legendary.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 26,
                            Title = "Dividend Aristocrat"
                        },
                        new
                        {
                            Id = 60,
                            Content = "Skyrizi and Rinvoq are more than compensating for Humira losses.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 27,
                            Title = "Post-Humira Transition"
                        },
                        new
                        {
                            Id = 61,
                            Content = "ABBV pays a strong dividend while still actively growing its pipeline.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 27,
                            Title = "High Dividend Yield"
                        },
                        new
                        {
                            Id = 62,
                            Content = "Recent bolt-on acquisitions show management is thinking long-term.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 27,
                            Title = "Acquisition Strategy"
                        },
                        new
                        {
                            Id = 63,
                            Content = "BAC is highly leveraged to interest rates — watch the Fed closely.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 28,
                            Title = "Rate Sensitivity"
                        },
                        new
                        {
                            Id = 64,
                            Content = "Massive consumer deposit base is a durable competitive advantage.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 28,
                            Title = "Consumer Banking"
                        },
                        new
                        {
                            Id = 65,
                            Content = "PG is boring in the best possible way. Reliable decade after decade.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 29,
                            Title = "Steady Compounder"
                        },
                        new
                        {
                            Id = 66,
                            Content = "Frito-Lay alone is arguably worth the entire investment in PepsiCo.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 30,
                            Title = "Snacks Powerhouse"
                        },
                        new
                        {
                            Id = 67,
                            Content = "Beverage volume softness is worth monitoring over the next few quarters.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 30,
                            Title = "Volume Pressure"
                        },
                        new
                        {
                            Id = 68,
                            Content = "Emerging market expansion is a quiet but steady growth engine.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 30,
                            Title = "International Growth"
                        },
                        new
                        {
                            Id = 69,
                            Content = "PEP has raised its dividend for over 50 years. Hard to ignore.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 30,
                            Title = "Dividend Growth"
                        },
                        new
                        {
                            Id = 70,
                            Content = "Agentforce could become a major new revenue stream for Salesforce.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 31,
                            Title = "AI Agents"
                        },
                        new
                        {
                            Id = 71,
                            Content = "Salesforce is finally delivering the profitability investors wanted.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 31,
                            Title = "Margin Expansion"
                        },
                        new
                        {
                            Id = 72,
                            Content = "Generative AI tools could commoditize parts of Adobe's creative suite.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 32,
                            Title = "AI Disruption Risk"
                        },
                        new
                        {
                            Id = 73,
                            Content = "New leadership needs to reinvigorate wholesale channels and product innovation.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 33,
                            Title = "Brand Turnaround"
                        },
                        new
                        {
                            Id = 74,
                            Content = "Any recovery in China consumer spending would significantly help NKE.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 33,
                            Title = "China Recovery"
                        },
                        new
                        {
                            Id = 75,
                            Content = "NKE is trading at a much more reasonable valuation than it was two years ago.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 33,
                            Title = "Valuation Reset"
                        },
                        new
                        {
                            Id = 76,
                            Content = "Disney+ finally turning profitable is a major long-awaited milestone.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 34,
                            Title = "Streaming Profitability"
                        },
                        new
                        {
                            Id = 77,
                            Content = "Theme park demand has stayed far stronger than many analysts expected.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 34,
                            Title = "Parks Resilience"
                        },
                        new
                        {
                            Id = 78,
                            Content = "Toyota's hybrid lineup keeps outselling pure EVs in most global markets.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 35,
                            Title = "Hybrid Leader"
                        },
                        new
                        {
                            Id = 79,
                            Content = "AZN's cancer drug portfolio is one of the very best in all of pharma.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 36,
                            Title = "Oncology Pipeline"
                        },
                        new
                        {
                            Id = 80,
                            Content = "AZN has meaningful China revenue which adds real political risk.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 36,
                            Title = "China Exposure"
                        },
                        new
                        {
                            Id = 81,
                            Content = "Rare disease acquisitions could add significant future revenue streams.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 36,
                            Title = "Rare Disease Bets"
                        },
                        new
                        {
                            Id = 82,
                            Content = "Tagrisso remains a dominant lung cancer treatment with strong revenue.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 36,
                            Title = "Tagrisso Growth"
                        },
                        new
                        {
                            Id = 83,
                            Content = "Intel Foundry is a massive multi-year bet that will take time to play out.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 37,
                            Title = "Foundry Bet"
                        },
                        new
                        {
                            Id = 84,
                            Content = "AMD and Arm-based chips keep eating into Intel's data center share.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 37,
                            Title = "Market Share Loss"
                        },
                        new
                        {
                            Id = 85,
                            Content = "Palantir's AI Platform is gaining strong momentum in enterprise.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 38,
                            Title = "AIP Traction"
                        },
                        new
                        {
                            Id = 86,
                            Content = "PLTR's valuation is extremely stretched relative to current revenue.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 38,
                            Title = "Valuation Debate"
                        },
                        new
                        {
                            Id = 87,
                            Content = "Defense and intelligence contracts provide very stable recurring revenue.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 38,
                            Title = "Government Contracts"
                        },
                        new
                        {
                            Id = 88,
                            Content = "Trading at low multiples makes BABA tempting for patient value investors.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 39,
                            Title = "Cheap Valuation"
                        },
                        new
                        {
                            Id = 89,
                            Content = "Pfizer is working hard to replace the massive lost COVID vaccine revenue.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 40,
                            Title = "Post-COVID Reset"
                        },
                        new
                        {
                            Id = 90,
                            Content = "Oncology-focused acquisitions could meaningfully restock the pipeline.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 40,
                            Title = "Pipeline Watch"
                        },
                        new
                        {
                            Id = 91,
                            Content = "CAT benefits directly from global infrastructure and construction spending.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 41,
                            Title = "Infrastructure Boom"
                        },
                        new
                        {
                            Id = 92,
                            Content = "Mining equipment demand remains strong with commodity prices elevated.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 41,
                            Title = "Mining Demand"
                        },
                        new
                        {
                            Id = 93,
                            Content = "CAT's aftermarket parts and services segment has incredible margins.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 41,
                            Title = "Services Growth"
                        },
                        new
                        {
                            Id = 94,
                            Content = "Order backlogs remain healthy pointing to strong revenue ahead.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 41,
                            Title = "Backlog Strength"
                        },
                        new
                        {
                            Id = 95,
                            Content = "AI data centers need massive networking upgrades — Cisco is well placed.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 42,
                            Title = "AI Networking"
                        },
                        new
                        {
                            Id = 96,
                            Content = "IBM's Red Hat continues to be a solid enterprise hybrid cloud play.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 43,
                            Title = "Hybrid Cloud Focus"
                        },
                        new
                        {
                            Id = 97,
                            Content = "watsonx is IBM's enterprise AI bet and early adoption signs are decent.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 43,
                            Title = "AI Consulting"
                        },
                        new
                        {
                            Id = 98,
                            Content = "IBM keeps paying a reliable dividend while quietly modernizing itself.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 43,
                            Title = "Steady Dividend"
                        },
                        new
                        {
                            Id = 99,
                            Content = "Investment banking deal flow is finally picking up after a tough cycle.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 44,
                            Title = "IB Recovery"
                        },
                        new
                        {
                            Id = 100,
                            Content = "Pulling back from consumer banking was clearly the right strategic call.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 44,
                            Title = "Consumer Exit"
                        },
                        new
                        {
                            Id = 101,
                            Content = "The asset-light franchise model generates incredibly consistent cash flow.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 45,
                            Title = "Franchise Model"
                        },
                        new
                        {
                            Id = 102,
                            Content = "New CEO Brian Niccol needs to fix both traffic trends and brand perception.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 46,
                            Title = "Turnaround Watch"
                        },
                        new
                        {
                            Id = 103,
                            Content = "China comp sales remain under heavy pressure from aggressive local rivals.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 46,
                            Title = "China Weakness"
                        },
                        new
                        {
                            Id = 104,
                            Content = "Cutting back the menu complexity is a smart operational move.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 46,
                            Title = "Menu Simplification"
                        },
                        new
                        {
                            Id = 105,
                            Content = "Starbucks Rewards membership is a genuinely powerful retention engine.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 46,
                            Title = "Loyalty Program"
                        },
                        new
                        {
                            Id = 106,
                            Content = "Parcel volume is slowly recovering as e-commerce spending stabilizes.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 47,
                            Title = "Volume Recovery"
                        },
                        new
                        {
                            Id = 107,
                            Content = "Amazon building its own logistics network is a serious long-term threat.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 47,
                            Title = "Amazon Risk"
                        },
                        new
                        {
                            Id = 108,
                            Content = "Blackstone keeps breaking records on assets under management every quarter.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 48,
                            Title = "AUM Growth"
                        },
                        new
                        {
                            Id = 109,
                            Content = "Arm-based Windows PCs powered by Snapdragon are genuinely gaining ground.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 49,
                            Title = "Snapdragon PC Push"
                        },
                        new
                        {
                            Id = 110,
                            Content = "Losing Apple as a modem customer was a more significant blow than expected.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 49,
                            Title = "Apple Dependency"
                        },
                        new
                        {
                            Id = 111,
                            Content = "Automotive chip wins are diversifying QCOM beyond just smartphones.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 49,
                            Title = "Auto Chips"
                        },
                        new
                        {
                            Id = 112,
                            Content = "FreeStyle Libre dominates the continuous glucose monitoring market globally.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 50,
                            Title = "CGM Leader"
                        },
                        new
                        {
                            Id = 113,
                            Content = "Abbott's mix of diagnostics, devices and nutrition is impressively balanced.",
                            CreatedOn = new DateTime(2026, 5, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            StockId = 50,
                            Title = "Diversified Medtech"
                        });
                });

            modelBuilder.Entity("StockApplicationApi.Models.RefreshTokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Nvidia",
                            Industry = "Semiconductors",
                            LastDiv = 0.16m,
                            MarketCap = 4300000000000L,
                            Purchase = 188.60m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Apple Inc",
                            Industry = "Technology",
                            LastDiv = 0.24m,
                            MarketCap = 3800000000000L,
                            Purchase = 260.45m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet",
                            Industry = "Technology",
                            LastDiv = 0.00m,
                            MarketCap = 3700000000000L,
                            Purchase = 315.70m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Microsoft",
                            Industry = "Technology",
                            LastDiv = 0.68m,
                            MarketCap = 2800000000000L,
                            Purchase = 370.80m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 2600000000000L,
                            Purchase = 238.40m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "TSMC",
                            Industry = "Semiconductors",
                            LastDiv = 1.20m,
                            MarketCap = 1900000000000L,
                            Purchase = 370.60m,
                            Symbol = "TSM"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Broadcom",
                            Industry = "Semiconductors",
                            LastDiv = 2.10m,
                            MarketCap = 1800000000000L,
                            Purchase = 371.50m,
                            Symbol = "AVGO"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Meta Platforms",
                            Industry = "Social Media",
                            LastDiv = 0.50m,
                            MarketCap = 1600000000000L,
                            Purchase = 629.80m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Tesla",
                            Industry = "Automotive",
                            LastDiv = 0.00m,
                            MarketCap = 1300000000000L,
                            Purchase = 348.90m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Berkshire Hathaway",
                            Industry = "Financials",
                            LastDiv = 0.00m,
                            MarketCap = 1030000000000L,
                            Purchase = 479.90m,
                            Symbol = "BRK-B"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Walmart",
                            Industry = "Retail",
                            LastDiv = 0.80m,
                            MarketCap = 1010000000000L,
                            Purchase = 126.70m,
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Eli Lilly",
                            Industry = "Healthcare",
                            LastDiv = 1.30m,
                            MarketCap = 887000000000L,
                            Purchase = 939.40m,
                            Symbol = "LLY"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "JPMorgan Chase",
                            Industry = "Financials",
                            LastDiv = 1.15m,
                            MarketCap = 835000000000L,
                            Purchase = 309.80m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Visa",
                            Industry = "Financials",
                            LastDiv = 0.52m,
                            MarketCap = 586000000000L,
                            Purchase = 304.30m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "Exxon Mobil",
                            Industry = "Energy",
                            LastDiv = 0.95m,
                            MarketCap = 633000000000L,
                            Purchase = 152.50m,
                            Symbol = "XOM"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "ASML Holding",
                            Industry = "Semiconductors",
                            LastDiv = 1.75m,
                            MarketCap = 580000000000L,
                            Purchase = 1478.00m,
                            Symbol = "ASML"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Tencent",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 578000000000L,
                            Purchase = 63.90m,
                            Symbol = "TCEHY"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Johnson & Johnson",
                            Industry = "Healthcare",
                            LastDiv = 1.19m,
                            MarketCap = 574000000000L,
                            Purchase = 238.40m,
                            Symbol = "JNJ"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Mastercard",
                            Industry = "Financials",
                            LastDiv = 0.66m,
                            MarketCap = 445000000000L,
                            Purchase = 498.60m,
                            Symbol = "MA"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Costco",
                            Industry = "Retail",
                            LastDiv = 1.02m,
                            MarketCap = 443000000000L,
                            Purchase = 998.40m,
                            Symbol = "COST"
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "Netflix",
                            Industry = "Entertainment",
                            LastDiv = 0.00m,
                            MarketCap = 436000000000L,
                            Purchase = 103.00m,
                            Symbol = "NFLX"
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "AMD",
                            Industry = "Semiconductors",
                            LastDiv = 0.00m,
                            MarketCap = 399000000000L,
                            Purchase = 245.00m,
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "Oracle",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 397000000000L,
                            Purchase = 138.00m,
                            Symbol = "ORCL"
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "Chevron",
                            Industry = "Energy",
                            LastDiv = 1.51m,
                            MarketCap = 375000000000L,
                            Purchase = 188.50m,
                            Symbol = "CVX"
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "Home Depot",
                            Industry = "Retail",
                            LastDiv = 2.25m,
                            MarketCap = 335000000000L,
                            Purchase = 337.30m,
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "Coca-Cola",
                            Industry = "Beverages",
                            LastDiv = 0.48m,
                            MarketCap = 333000000000L,
                            Purchase = 77.40m,
                            Symbol = "KO"
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "AbbVie",
                            Industry = "Healthcare",
                            LastDiv = 1.55m,
                            MarketCap = 367000000000L,
                            Purchase = 207.90m,
                            Symbol = "ABBV"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Bank of America",
                            Industry = "Financials",
                            LastDiv = 0.24m,
                            MarketCap = 377000000000L,
                            Purchase = 52.50m,
                            Symbol = "BAC"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Procter & Gamble",
                            Industry = "Consumer Goods",
                            LastDiv = 0.94m,
                            MarketCap = 339000000000L,
                            Purchase = 145.10m,
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "PepsiCo",
                            Industry = "Beverages",
                            LastDiv = 1.26m,
                            MarketCap = 231000000000L,
                            Purchase = 168.20m,
                            Symbol = "PEP"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "Salesforce",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 285000000000L,
                            Purchase = 295.40m,
                            Symbol = "CRM"
                        },
                        new
                        {
                            Id = 32,
                            CompanyName = "Adobe",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 262000000000L,
                            Purchase = 585.10m,
                            Symbol = "ADBE"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Nike",
                            Industry = "Apparel",
                            LastDiv = 0.37m,
                            MarketCap = 153000000000L,
                            Purchase = 101.50m,
                            Symbol = "NKE"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Disney",
                            Industry = "Entertainment",
                            LastDiv = 0.30m,
                            MarketCap = 205000000000L,
                            Purchase = 112.80m,
                            Symbol = "DIS"
                        },
                        new
                        {
                            Id = 35,
                            CompanyName = "Toyota",
                            Industry = "Automotive",
                            LastDiv = 0.85m,
                            MarketCap = 274000000000L,
                            Purchase = 210.60m,
                            Symbol = "TM"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "AstraZeneca",
                            Industry = "Healthcare",
                            LastDiv = 1.90m,
                            MarketCap = 316000000000L,
                            Purchase = 204.00m,
                            Symbol = "AZN"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Intel",
                            Industry = "Semiconductors",
                            LastDiv = 0.12m,
                            MarketCap = 313000000000L,
                            Purchase = 62.30m,
                            Symbol = "INTC"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Palantir",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 306000000000L,
                            Purchase = 128.00m,
                            Symbol = "PLTR"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Alibaba",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 304000000000L,
                            Purchase = 127.30m,
                            Symbol = "BABA"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Pfizer",
                            Industry = "Healthcare",
                            LastDiv = 0.42m,
                            MarketCap = 161000000000L,
                            Purchase = 28.50m,
                            Symbol = "PFE"
                        },
                        new
                        {
                            Id = 41,
                            CompanyName = "Caterpillar",
                            Industry = "Industrials",
                            LastDiv = 1.30m,
                            MarketCap = 370000000000L,
                            Purchase = 790.60m,
                            Symbol = "CAT"
                        },
                        new
                        {
                            Id = 42,
                            CompanyName = "Cisco",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 324000000000L,
                            Purchase = 82.20m,
                            Symbol = "CSCO"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "IBM",
                            Industry = "Technology",
                            LastDiv = 1.66m,
                            MarketCap = 170000000000L,
                            Purchase = 185.30m,
                            Symbol = "IBM"
                        },
                        new
                        {
                            Id = 44,
                            CompanyName = "Goldman Sachs",
                            Industry = "Financials",
                            LastDiv = 2.75m,
                            MarketCap = 269000000000L,
                            Purchase = 907.80m,
                            Symbol = "GS"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "McDonald's",
                            Industry = "Restaurants",
                            LastDiv = 1.67m,
                            MarketCap = 210000000000L,
                            Purchase = 290.40m,
                            Symbol = "MCD"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Starbucks",
                            Industry = "Restaurants",
                            LastDiv = 0.57m,
                            MarketCap = 105000000000L,
                            Purchase = 92.50m,
                            Symbol = "SBUX"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "UPS",
                            Industry = "Logistics",
                            LastDiv = 1.63m,
                            MarketCap = 125000000000L,
                            Purchase = 145.80m,
                            Symbol = "UPS"
                        },
                        new
                        {
                            Id = 48,
                            CompanyName = "Blackstone",
                            Industry = "Financials",
                            LastDiv = 0.82m,
                            MarketCap = 158000000000L,
                            Purchase = 130.20m,
                            Symbol = "BX"
                        },
                        new
                        {
                            Id = 49,
                            CompanyName = "Qualcomm",
                            Industry = "Semiconductors",
                            LastDiv = 0.80m,
                            MarketCap = 190000000000L,
                            Purchase = 170.50m,
                            Symbol = "QCOM"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "Abbott Labs",
                            Industry = "Healthcare",
                            LastDiv = 0.55m,
                            MarketCap = 201000000000L,
                            Purchase = 115.40m,
                            Symbol = "ABT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", "AppUser")
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId");

                    b.HasOne("StockApplicationApi.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockApplicationApi.Models.RefreshTokens.RefreshToken", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("StockApplicationApi.Models.AppUser", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
