// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApplicationApi.Database;

#nullable disable

namespace StockApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322090446_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Apple Inc",
                            Industry = "Technology",
                            LastDiv = 0.24m,
                            MarketCap = 2800000000000L,
                            Purchase = 175.50m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Microsoft",
                            Industry = "Technology",
                            LastDiv = 0.68m,
                            MarketCap = 3000000000000L,
                            Purchase = 320.10m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet",
                            Industry = "Technology",
                            LastDiv = 0.00m,
                            MarketCap = 1800000000000L,
                            Purchase = 140.25m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Amazon",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 1600000000000L,
                            Purchase = 155.80m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Tesla",
                            Industry = "Automotive",
                            LastDiv = 0.00m,
                            MarketCap = 700000000000L,
                            Purchase = 210.40m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "Nvidia",
                            Industry = "Semiconductors",
                            LastDiv = 0.16m,
                            MarketCap = 2200000000000L,
                            Purchase = 600.75m,
                            Symbol = "NVDA"
                        });
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.HasOne("StockApplicationApi.Models.Stock", "Stocks")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
