// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockApplicationApi.Database;

#nullable disable

namespace StockApplicationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Nobody is catching NVDA on hardware. Blackwell is already sold out for the next 4 quarters.",
                            CreatedOn = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "GPU Lead is Insane"
                        },
                        new
                        {
                            Id = 2,
                            Content = "RSI is screaming overbought. I'm waiting for a 5% pullback before adding more.",
                            CreatedOn = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Overbought?"
                        },
                        new
                        {
                            Id = 3,
                            Content = "iPhone sales are flat, but the services revenue (App Store/iCloud) is where the real margin is.",
                            CreatedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Services is the play"
                        },
                        new
                        {
                            Id = 4,
                            Content = "The ecosystem lock-in is still the best in the world. Holding for the long term.",
                            CreatedOn = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Walled Garden"
                        },
                        new
                        {
                            Id = 5,
                            Content = "The new multimodal search is actually starting to steal market share back from the competitors.",
                            CreatedOn = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "Gemini Integration"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Digital ad spend is recovering. GOOGL is the primary beneficiary here.",
                            CreatedOn = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "Ad Spend"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Microsoft Cloud growth is decelerating slightly, but still dominant in enterprise.",
                            CreatedOn = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "Azure Cloud"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Reliable as always. Not a moonshot, but a bedrock for any portfolio.",
                            CreatedOn = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "Dividends"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Amazon's last-mile delivery costs are dropping. Expect a beat on earnings.",
                            CreatedOn = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "Logistics Cost"
                        },
                        new
                        {
                            Id = 10,
                            Content = "AWS is basically a money printing machine at this point. Offsetting the retail losses.",
                            CreatedOn = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "AWS Margin"
                        },
                        new
                        {
                            Id = 11,
                            Content = "TSMC is the best company in the world, but the China-Taiwan tension makes me nervous.",
                            CreatedOn = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 6,
                            Title = "Geopolitical Risk"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Reports show 3nm yields are better than expected. Huge for the next gen chips.",
                            CreatedOn = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 6,
                            Title = "3nm Yields"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Broadcom is the quiet winner of the AI race. Those custom ASICs are high margin.",
                            CreatedOn = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 7,
                            Title = "Networking Boom"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Meta's pivot back to its core ad business was the right move. Reels monetization is up.",
                            CreatedOn = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 8,
                            Title = "Ad Recovery"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Version 13 of FSD is actually usable. If they solve autonomy, the PE ratio makes sense.",
                            CreatedOn = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 9,
                            Title = "FSD Progress"
                        },
                        new
                        {
                            Id = 16,
                            Content = "BYD and Xiaomi are eating Tesla's lunch in China. Scary trend.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 9,
                            Title = "Competition"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Zepbound demand is through the roof. LLY is now a biotech powerhouse.",
                            CreatedOn = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 12,
                            Title = "Weight Loss Drugs"
                        },
                        new
                        {
                            Id = 18,
                            Content = "ASML literally has a monopoly on high-end lithography. You can't bet against them.",
                            CreatedOn = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 16,
                            Title = "EUV Dominance"
                        },
                        new
                        {
                            Id = 19,
                            Content = "AMD is consistently taking server market share. EPYC chips are superior.",
                            CreatedOn = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 22,
                            Title = "AMD vs Intel"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Palantir's bootcamps are converting customers fast. The growth is finally here.",
                            CreatedOn = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 38,
                            Title = "AIP Adoption"
                        },
                        new
                        {
                            Id = 21,
                            Content = "If the economy slows down, everyone goes to Walmart. Safest stock right now.",
                            CreatedOn = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 11,
                            Title = "Defensive Play"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Higher for longer means JPM keeps printing net interest income.",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 13,
                            Title = "Interest Rates"
                        },
                        new
                        {
                            Id = 23,
                            Content = "Brent oil hitting $90 is great for Exxon's cash flow.",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 15,
                            Title = "Oil Prices"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Costco just raised the membership fee and nobody left. That is brand power.",
                            CreatedOn = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 20,
                            Title = "Membership Growth"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Doesn't matter if it's a recession or a boom, people drink Coke.",
                            CreatedOn = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 26,
                            Title = "Dividend King"
                        },
                        new
                        {
                            Id = 26,
                            Content = "Nike is losing its edge to Hoka and On. Need more innovation in the lineup.",
                            CreatedOn = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 33,
                            Title = "Brand Fatigue"
                        },
                        new
                        {
                            Id = 27,
                            Content = "Disney+ is finally profitable, but the parks are carrying the whole company.",
                            CreatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 34,
                            Title = "Streaming Losses"
                        },
                        new
                        {
                            Id = 28,
                            Content = "MCD is the ultimate inflation hedge. People still need cheap calories.",
                            CreatedOn = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 45,
                            Title = "Global Scale"
                        },
                        new
                        {
                            Id = 29,
                            Content = "Intel is a 5-year play. If they can build a foundry business, they win.",
                            CreatedOn = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 37,
                            Title = "Foundry Dreams"
                        },
                        new
                        {
                            Id = 30,
                            Content = "Chevron's 4% yield is why I hold it. Solid management and buybacks.",
                            CreatedOn = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 24,
                            Title = "Yield Play"
                        },
                        new
                        {
                            Id = 31,
                            Content = "Buffett is sitting on a massive cash pile. Waiting for a crash to buy.",
                            CreatedOn = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 10,
                            Title = "Cash Pile"
                        },
                        new
                        {
                            Id = 32,
                            Content = "Visa is benefiting from the huge spike in international travel spending.",
                            CreatedOn = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 14,
                            Title = "Travel Rebound"
                        },
                        new
                        {
                            Id = 33,
                            Content = "Mastercard isn't scared of crypto. They are integrating it. Smart.",
                            CreatedOn = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 19,
                            Title = "Fintech Fear"
                        },
                        new
                        {
                            Id = 34,
                            Content = "Netflix password sharing ban worked. Subscribers are way up.",
                            CreatedOn = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 21,
                            Title = "Password Crackdown"
                        },
                        new
                        {
                            Id = 35,
                            Content = "Oracle is no longer a legacy company. Their OCI is actually good.",
                            CreatedOn = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 23,
                            Title = "Cloud Pivot"
                        },
                        new
                        {
                            Id = 36,
                            Content = "High interest rates are hurting Home Depot. People aren't remodeling.",
                            CreatedOn = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 25,
                            Title = "Housing Market"
                        },
                        new
                        {
                            Id = 37,
                            Content = "Salesforce is struggling to find new growth. The AI pivot needs to work.",
                            CreatedOn = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 31,
                            Title = "SaaS Saturation"
                        },
                        new
                        {
                            Id = 38,
                            Content = "Investment banking is waking up. Good news for Goldman.",
                            CreatedOn = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 44,
                            Title = "M&A Activity"
                        },
                        new
                        {
                            Id = 39,
                            Content = "Starbucks is getting crushed by local competition in China. Concern.",
                            CreatedOn = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 46,
                            Title = "China Headwinds"
                        },
                        new
                        {
                            Id = 40,
                            Content = "Caterpillar is the main play for the US infrastructure rebuild.",
                            CreatedOn = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 41,
                            Title = "Infrastructure Bill"
                        },
                        new
                        {
                            Id = 41,
                            Content = "Compute is the new oil, and Nvidia owns the wells.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "The New Gold"
                        },
                        new
                        {
                            Id = 42,
                            Content = "If Eli Lilly can fix the Zepbound supply, this hits $1000 easily.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 12,
                            Title = "Supply Chain"
                        },
                        new
                        {
                            Id = 43,
                            Content = "Adobe's AI tools are preventing users from switching to Canva.",
                            CreatedOn = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 32,
                            Title = "Firefly AI"
                        },
                        new
                        {
                            Id = 44,
                            Content = "Toyota was right about hybrids. Everyone is dumping pure EVs for them.",
                            CreatedOn = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 35,
                            Title = "Hybrid Strategy"
                        },
                        new
                        {
                            Id = 45,
                            Content = "BABA is trading at a ridiculous multiple. Too cheap to ignore.",
                            CreatedOn = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 39,
                            Title = "Deep Value"
                        },
                        new
                        {
                            Id = 46,
                            Content = "Pfizer needs a new blockbuster drug. COVID revenue is long gone.",
                            CreatedOn = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 40,
                            Title = "Pipeline Woes"
                        },
                        new
                        {
                            Id = 47,
                            Content = "Cisco's acquisition of Splunk is a game changer for their security stack.",
                            CreatedOn = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 42,
                            Title = "Security Growth"
                        },
                        new
                        {
                            Id = 48,
                            Content = "UPS is aggressively automating hubs to lower union labor costs.",
                            CreatedOn = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 47,
                            Title = "Automation"
                        },
                        new
                        {
                            Id = 49,
                            Content = "Blackstone is dominating the private credit market. High yields.",
                            CreatedOn = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 48,
                            Title = "Private Credit"
                        },
                        new
                        {
                            Id = 50,
                            Content = "Premium smartphone market is rebounding, helping Qualcomm's bottom line.",
                            CreatedOn = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 49,
                            Title = "Handset Recovery"
                        },
                        new
                        {
                            Id = 51,
                            Content = "Vision Pro is a tech marvel, but who is actually buying it for $3500?",
                            CreatedOn = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "VR/AR Doubt"
                        },
                        new
                        {
                            Id = 52,
                            Content = "Once a company uses Teams and Excel, they never leave. Wide moat.",
                            CreatedOn = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 4,
                            Title = "Enterprise Stickiness"
                        },
                        new
                        {
                            Id = 53,
                            Content = "Amazon's ad business is growing faster than Google's. High margin.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 5,
                            Title = "Advertising Growth"
                        },
                        new
                        {
                            Id = 54,
                            Content = "J&J still has the talc powder lawsuits hanging over them. Risky.",
                            CreatedOn = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 18,
                            Title = "Litigation Risks"
                        },
                        new
                        {
                            Id = 55,
                            Content = "Pepsi is more of a snack company than a soda company now. I love it.",
                            CreatedOn = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 30,
                            Title = "Snack Power"
                        },
                        new
                        {
                            Id = 56,
                            Content = "P&G has 60 years of dividend increases. Hard to beat that record.",
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 29,
                            Title = "Consumer Staple"
                        },
                        new
                        {
                            Id = 57,
                            Content = "AstraZeneca is the leader in targeted cancer treatments. Huge moat.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 36,
                            Title = "Oncology Lead"
                        },
                        new
                        {
                            Id = 58,
                            Content = "IBM is boring, but it pays a great dividend and the cloud is stable.",
                            CreatedOn = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 43,
                            Title = "Hybrid Cloud"
                        },
                        new
                        {
                            Id = 59,
                            Content = "Abbott's Freestyle Libre is the gold standard for glucose monitoring.",
                            CreatedOn = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 50,
                            Title = "MedTech Play"
                        },
                        new
                        {
                            Id = 60,
                            Content = "Gross margins at 75% for a hardware company? Simply unheard of.",
                            CreatedOn = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 1,
                            Title = "Margin Expansion"
                        },
                        new
                        {
                            Id = 61,
                            Content = "Tencent is finally seeing the regulatory environment ease in China.",
                            CreatedOn = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 17,
                            Title = "Gaming Regulation"
                        },
                        new
                        {
                            Id = 62,
                            Content = "BAC is the most rate-sensitive big bank. If rates drop, they suffer.",
                            CreatedOn = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 28,
                            Title = "Net Interest Margin"
                        },
                        new
                        {
                            Id = 63,
                            Content = "AbbVie is handling the loss of patent protection better than expected.",
                            CreatedOn = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 27,
                            Title = "Humira Cliff"
                        },
                        new
                        {
                            Id = 64,
                            Content = "Dimon is the best CEO in banking. Period.",
                            CreatedOn = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 13,
                            Title = "Fortress Balance Sheet"
                        },
                        new
                        {
                            Id = 65,
                            Content = "The VMware integration into Broadcom is finally yielding efficiency.",
                            CreatedOn = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 7,
                            Title = "VMware Synergy"
                        },
                        new
                        {
                            Id = 66,
                            Content = "Shorts is finally monetizing well enough to compete with TikTok.",
                            CreatedOn = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 3,
                            Title = "YouTube Shorts"
                        },
                        new
                        {
                            Id = 67,
                            Content = "AMD's MI300X is the only real alternative to H100s right now.",
                            CreatedOn = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 22,
                            Title = "Data Center AI"
                        },
                        new
                        {
                            Id = 68,
                            Content = "PLTR isn't just for the government anymore. Commercial is exploding.",
                            CreatedOn = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 38,
                            Title = "Commercial Growth"
                        },
                        new
                        {
                            Id = 69,
                            Content = "Everything depends on the August reveal. Pure speculation till then.",
                            CreatedOn = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 9,
                            Title = "Robotaxi Event"
                        },
                        new
                        {
                            Id = 70,
                            Content = "Another $100B in buybacks. Apple is a financial engineering masterpiece.",
                            CreatedOn = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockId = 2,
                            Title = "Buyback Machine"
                        });
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LastDiv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("MarketCap")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Nvidia",
                            Industry = "Semiconductors",
                            LastDiv = 0.16m,
                            MarketCap = 4300000000000L,
                            Purchase = 188.60m,
                            Symbol = "NVDA"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Apple Inc",
                            Industry = "Technology",
                            LastDiv = 0.24m,
                            MarketCap = 3800000000000L,
                            Purchase = 260.45m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Alphabet",
                            Industry = "Technology",
                            LastDiv = 0.00m,
                            MarketCap = 3700000000000L,
                            Purchase = 315.70m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 4,
                            CompanyName = "Microsoft",
                            Industry = "Technology",
                            LastDiv = 0.68m,
                            MarketCap = 2800000000000L,
                            Purchase = 370.80m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 5,
                            CompanyName = "Amazon",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 2600000000000L,
                            Purchase = 238.40m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 6,
                            CompanyName = "TSMC",
                            Industry = "Semiconductors",
                            LastDiv = 1.20m,
                            MarketCap = 1900000000000L,
                            Purchase = 370.60m,
                            Symbol = "TSM"
                        },
                        new
                        {
                            Id = 7,
                            CompanyName = "Broadcom",
                            Industry = "Semiconductors",
                            LastDiv = 2.10m,
                            MarketCap = 1800000000000L,
                            Purchase = 371.50m,
                            Symbol = "AVGO"
                        },
                        new
                        {
                            Id = 8,
                            CompanyName = "Meta Platforms",
                            Industry = "Social Media",
                            LastDiv = 0.50m,
                            MarketCap = 1600000000000L,
                            Purchase = 629.80m,
                            Symbol = "META"
                        },
                        new
                        {
                            Id = 9,
                            CompanyName = "Tesla",
                            Industry = "Automotive",
                            LastDiv = 0.00m,
                            MarketCap = 1300000000000L,
                            Purchase = 348.90m,
                            Symbol = "TSLA"
                        },
                        new
                        {
                            Id = 10,
                            CompanyName = "Berkshire Hathaway",
                            Industry = "Financials",
                            LastDiv = 0.00m,
                            MarketCap = 1030000000000L,
                            Purchase = 479.90m,
                            Symbol = "BRK-B"
                        },
                        new
                        {
                            Id = 11,
                            CompanyName = "Walmart",
                            Industry = "Retail",
                            LastDiv = 0.80m,
                            MarketCap = 1010000000000L,
                            Purchase = 126.70m,
                            Symbol = "WMT"
                        },
                        new
                        {
                            Id = 12,
                            CompanyName = "Eli Lilly",
                            Industry = "Healthcare",
                            LastDiv = 1.30m,
                            MarketCap = 887000000000L,
                            Purchase = 939.40m,
                            Symbol = "LLY"
                        },
                        new
                        {
                            Id = 13,
                            CompanyName = "JPMorgan Chase",
                            Industry = "Financials",
                            LastDiv = 1.15m,
                            MarketCap = 835000000000L,
                            Purchase = 309.80m,
                            Symbol = "JPM"
                        },
                        new
                        {
                            Id = 14,
                            CompanyName = "Visa",
                            Industry = "Financials",
                            LastDiv = 0.52m,
                            MarketCap = 586000000000L,
                            Purchase = 304.30m,
                            Symbol = "V"
                        },
                        new
                        {
                            Id = 15,
                            CompanyName = "Exxon Mobil",
                            Industry = "Energy",
                            LastDiv = 0.95m,
                            MarketCap = 633000000000L,
                            Purchase = 152.50m,
                            Symbol = "XOM"
                        },
                        new
                        {
                            Id = 16,
                            CompanyName = "ASML Holding",
                            Industry = "Semiconductors",
                            LastDiv = 1.75m,
                            MarketCap = 580000000000L,
                            Purchase = 1478.00m,
                            Symbol = "ASML"
                        },
                        new
                        {
                            Id = 17,
                            CompanyName = "Tencent",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 578000000000L,
                            Purchase = 63.90m,
                            Symbol = "TCEHY"
                        },
                        new
                        {
                            Id = 18,
                            CompanyName = "Johnson & Johnson",
                            Industry = "Healthcare",
                            LastDiv = 1.19m,
                            MarketCap = 574000000000L,
                            Purchase = 238.40m,
                            Symbol = "JNJ"
                        },
                        new
                        {
                            Id = 19,
                            CompanyName = "Mastercard",
                            Industry = "Financials",
                            LastDiv = 0.66m,
                            MarketCap = 445000000000L,
                            Purchase = 498.60m,
                            Symbol = "MA"
                        },
                        new
                        {
                            Id = 20,
                            CompanyName = "Costco",
                            Industry = "Retail",
                            LastDiv = 1.02m,
                            MarketCap = 443000000000L,
                            Purchase = 998.40m,
                            Symbol = "COST"
                        },
                        new
                        {
                            Id = 21,
                            CompanyName = "Netflix",
                            Industry = "Entertainment",
                            LastDiv = 0.00m,
                            MarketCap = 436000000000L,
                            Purchase = 103.00m,
                            Symbol = "NFLX"
                        },
                        new
                        {
                            Id = 22,
                            CompanyName = "AMD",
                            Industry = "Semiconductors",
                            LastDiv = 0.00m,
                            MarketCap = 399000000000L,
                            Purchase = 245.00m,
                            Symbol = "AMD"
                        },
                        new
                        {
                            Id = 23,
                            CompanyName = "Oracle",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 397000000000L,
                            Purchase = 138.00m,
                            Symbol = "ORCL"
                        },
                        new
                        {
                            Id = 24,
                            CompanyName = "Chevron",
                            Industry = "Energy",
                            LastDiv = 1.51m,
                            MarketCap = 375000000000L,
                            Purchase = 188.50m,
                            Symbol = "CVX"
                        },
                        new
                        {
                            Id = 25,
                            CompanyName = "Home Depot",
                            Industry = "Retail",
                            LastDiv = 2.25m,
                            MarketCap = 335000000000L,
                            Purchase = 337.30m,
                            Symbol = "HD"
                        },
                        new
                        {
                            Id = 26,
                            CompanyName = "Coca-Cola",
                            Industry = "Beverages",
                            LastDiv = 0.48m,
                            MarketCap = 333000000000L,
                            Purchase = 77.40m,
                            Symbol = "KO"
                        },
                        new
                        {
                            Id = 27,
                            CompanyName = "AbbVie",
                            Industry = "Healthcare",
                            LastDiv = 1.55m,
                            MarketCap = 367000000000L,
                            Purchase = 207.90m,
                            Symbol = "ABBV"
                        },
                        new
                        {
                            Id = 28,
                            CompanyName = "Bank of America",
                            Industry = "Financials",
                            LastDiv = 0.24m,
                            MarketCap = 377000000000L,
                            Purchase = 52.50m,
                            Symbol = "BAC"
                        },
                        new
                        {
                            Id = 29,
                            CompanyName = "Procter & Gamble",
                            Industry = "Consumer Goods",
                            LastDiv = 0.94m,
                            MarketCap = 339000000000L,
                            Purchase = 145.10m,
                            Symbol = "PG"
                        },
                        new
                        {
                            Id = 30,
                            CompanyName = "PepsiCo",
                            Industry = "Beverages",
                            LastDiv = 1.26m,
                            MarketCap = 231000000000L,
                            Purchase = 168.20m,
                            Symbol = "PEP"
                        },
                        new
                        {
                            Id = 31,
                            CompanyName = "Salesforce",
                            Industry = "Software",
                            LastDiv = 0.40m,
                            MarketCap = 285000000000L,
                            Purchase = 295.40m,
                            Symbol = "CRM"
                        },
                        new
                        {
                            Id = 32,
                            CompanyName = "Adobe",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 262000000000L,
                            Purchase = 585.10m,
                            Symbol = "ADBE"
                        },
                        new
                        {
                            Id = 33,
                            CompanyName = "Nike",
                            Industry = "Apparel",
                            LastDiv = 0.37m,
                            MarketCap = 153000000000L,
                            Purchase = 101.50m,
                            Symbol = "NKE"
                        },
                        new
                        {
                            Id = 34,
                            CompanyName = "Disney",
                            Industry = "Entertainment",
                            LastDiv = 0.30m,
                            MarketCap = 205000000000L,
                            Purchase = 112.80m,
                            Symbol = "DIS"
                        },
                        new
                        {
                            Id = 35,
                            CompanyName = "Toyota",
                            Industry = "Automotive",
                            LastDiv = 0.85m,
                            MarketCap = 274000000000L,
                            Purchase = 210.60m,
                            Symbol = "TM"
                        },
                        new
                        {
                            Id = 36,
                            CompanyName = "AstraZeneca",
                            Industry = "Healthcare",
                            LastDiv = 1.90m,
                            MarketCap = 316000000000L,
                            Purchase = 204.00m,
                            Symbol = "AZN"
                        },
                        new
                        {
                            Id = 37,
                            CompanyName = "Intel",
                            Industry = "Semiconductors",
                            LastDiv = 0.12m,
                            MarketCap = 313000000000L,
                            Purchase = 62.30m,
                            Symbol = "INTC"
                        },
                        new
                        {
                            Id = 38,
                            CompanyName = "Palantir",
                            Industry = "Software",
                            LastDiv = 0.00m,
                            MarketCap = 306000000000L,
                            Purchase = 128.00m,
                            Symbol = "PLTR"
                        },
                        new
                        {
                            Id = 39,
                            CompanyName = "Alibaba",
                            Industry = "E-Commerce",
                            LastDiv = 0.00m,
                            MarketCap = 304000000000L,
                            Purchase = 127.30m,
                            Symbol = "BABA"
                        },
                        new
                        {
                            Id = 40,
                            CompanyName = "Pfizer",
                            Industry = "Healthcare",
                            LastDiv = 0.42m,
                            MarketCap = 161000000000L,
                            Purchase = 28.50m,
                            Symbol = "PFE"
                        },
                        new
                        {
                            Id = 41,
                            CompanyName = "Caterpillar",
                            Industry = "Industrials",
                            LastDiv = 1.30m,
                            MarketCap = 370000000000L,
                            Purchase = 790.60m,
                            Symbol = "CAT"
                        },
                        new
                        {
                            Id = 42,
                            CompanyName = "Cisco",
                            Industry = "Technology",
                            LastDiv = 0.40m,
                            MarketCap = 324000000000L,
                            Purchase = 82.20m,
                            Symbol = "CSCO"
                        },
                        new
                        {
                            Id = 43,
                            CompanyName = "IBM",
                            Industry = "Technology",
                            LastDiv = 1.66m,
                            MarketCap = 170000000000L,
                            Purchase = 185.30m,
                            Symbol = "IBM"
                        },
                        new
                        {
                            Id = 44,
                            CompanyName = "Goldman Sachs",
                            Industry = "Financials",
                            LastDiv = 2.75m,
                            MarketCap = 269000000000L,
                            Purchase = 907.80m,
                            Symbol = "GS"
                        },
                        new
                        {
                            Id = 45,
                            CompanyName = "McDonald's",
                            Industry = "Restaurants",
                            LastDiv = 1.67m,
                            MarketCap = 210000000000L,
                            Purchase = 290.40m,
                            Symbol = "MCD"
                        },
                        new
                        {
                            Id = 46,
                            CompanyName = "Starbucks",
                            Industry = "Restaurants",
                            LastDiv = 0.57m,
                            MarketCap = 105000000000L,
                            Purchase = 92.50m,
                            Symbol = "SBUX"
                        },
                        new
                        {
                            Id = 47,
                            CompanyName = "UPS",
                            Industry = "Logistics",
                            LastDiv = 1.63m,
                            MarketCap = 125000000000L,
                            Purchase = 145.80m,
                            Symbol = "UPS"
                        },
                        new
                        {
                            Id = 48,
                            CompanyName = "Blackstone",
                            Industry = "Financials",
                            LastDiv = 0.82m,
                            MarketCap = 158000000000L,
                            Purchase = 130.20m,
                            Symbol = "BX"
                        },
                        new
                        {
                            Id = 49,
                            CompanyName = "Qualcomm",
                            Industry = "Semiconductors",
                            LastDiv = 0.80m,
                            MarketCap = 190000000000L,
                            Purchase = 170.50m,
                            Symbol = "QCOM"
                        },
                        new
                        {
                            Id = 50,
                            CompanyName = "Abbott Labs",
                            Industry = "Healthcare",
                            LastDiv = 0.55m,
                            MarketCap = 201000000000L,
                            Purchase = 115.40m,
                            Symbol = "ABT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockApplicationApi.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockApplicationApi.Models.Comment", b =>
                {
                    b.HasOne("StockApplicationApi.Models.Stock", null)
                        .WithMany("Comments")
                        .HasForeignKey("StockId");
                });

            modelBuilder.Entity("StockApplicationApi.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
