name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore StockApplication.sln

      - name: Build
        run: dotnet build StockApplication.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test StockApplication.sln --no-build --configuration Release --verbosity normal